#!/bin/bash

DPATH=${DPATH:-`dirname ${0}`}
JARNAME="ccgrep.jar"

if [ "$DPATH" == "/usr/local/bin" ]; then
  DPATH="/usr/local/lib/ccgrep"
fi

if [ -f "$DPATH/$JARNAME" ]; then
  java -jar "$DPATH/$JARNAME" "$@"
else
  echo "$JARNAME not found."
  exit 2
fi
