#!/bin/bash

INSTPATH="/usr/local/lib/ccgrep"
BINPATH="/usr/local/bin"

echo -n removing...
rm -f "$BINPATH/ccgrep"
rm -f "$INSTPATH/install"
rm -f "$INSTPATH/LICENSE.txt"
rm -f "$INSTPATH/README.md"
rm -f "$INSTPATH/CCGrep.jar"
rm -f "$INSTPATH/ccgrep"
rm -fd "$INSTPATH"
echo finish.

if [ "$1" != "clean" ]; then
    echo -n installing...
    FROMPATH=${FROMPATH:-`dirname ${0}`}
    mkdir "$INSTPATH"
    #cp -r "$FROMPATH/lib/" "$INSTPATH"
    #cp -r "$FROMPATH/src/" "$INSTPATH"
    cp "$FROMPATH/install" "$INSTPATH"
    cp "$FROMPATH/LICENSE.txt" "$INSTPATH"
    cp "$FROMPATH/README.md" "$INSTPATH"
    cp "$FROMPATH/CCGrep.jar" "$INSTPATH"
    cp "$FROMPATH/ccgrep" "$INSTPATH"
    cp "$FROMPATH/ccgrep" "$BINPATH"
    chmod a+x "$BINPATH/ccgrep"
    echo finish.
fi
echo successful.
