#!/bin/bash

INSTPATH="/usr/local/lib/ccgrep/"
BINPATH="/usr/local/bin"

rm -fv "$BINPATH/ccgrep"
rm -rfv "$INSTPATH"

if [ "$1" != "clean" ]; then
    echo installing...
    FROMPATH=${FROMPATH:-`dirname ${0}`}
    mkdir "$INSTPATH"
    #cp -r "$FROMPATH/lib/" "$INSTPATH"
    #cp -r "$FROMPATH/src/" "$INSTPATH"
    cp "$FROMPATH/install" "$INSTPATH"
    cp "$FROMPATH/LICENSE.txt" "$INSTPATH"
    cp "$FROMPATH/README.md" "$INSTPATH"
    cp "$FROMPATH/CCGrep.jar" "$INSTPATH"
    cp "$FROMPATH/ccgrep" "$BINPATH"
    chmod a+x "$BINPATH/ccgrep"
    echo finish.
fi
