#!/bin/bash

INSTPATH="/usr/local/lib/ccgrep"
BINPATH="/usr/local/bin"

echo removing old files...
rm -f "$BINPATH/ccgrep"
rm -f "$INSTPATH/install"
rm -f "$INSTPATH/LICENSE.txt"
rm -f "$INSTPATH/README.md"
rm -f "$INSTPATH/CCGrep.jar"
rm -f "$INSTPATH/ccgrep"

if [ "$1" != "clean" ]; then
    echo installing...
    FROMPATH=${FROMPATH:-`dirname ${0}`}
    mkdir -p "$INSTPATH"
    mkdir -p "$BINPATH"
    cp "$FROMPATH/install" "$INSTPATH"
    cp "$FROMPATH/LICENSE.txt" "$INSTPATH"
    cp "$FROMPATH/README.md" "$INSTPATH"
    cp "$FROMPATH/CCGrep.jar" "$INSTPATH"
    cp "$FROMPATH/ccgrep" "$INSTPATH"
    cp "$FROMPATH/ccgrep" "$BINPATH"
    chmod a+x "$BINPATH/ccgrep"
fi
